// src/features/candidate/pages/LearningHubPage.jsx
import React, { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  Paper,
  Grid,
  TextField,
  InputAdornment,
  Button,
  Chip,
  Card,
  CardContent,
  CardActions,
  CardMedia,
  IconButton,
  Tabs,
  Tab,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  CircularProgress,
  Stack,
  Tooltip,
  Avatar,
  LinearProgress,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Rating,
  Snackbar,
  Alert,
} from '@mui/material';
import {
  Search as SearchIcon,
  FilterList as FilterIcon,
  Favorite as FavoriteIcon,
  FavoriteBorder as FavoriteBorderIcon,
  PlayArrow as PlayArrowIcon,
  Article as ArticleIcon,
  Quiz as QuizIcon,
  Timer as TimerIcon,
  Visibility as VisibilityIcon,
  TrendingUp as TrendingUpIcon,
  School as SchoolIcon,
  CheckCircle as CheckCircleIcon,
  Cancel as CancelIcon,
  AccessTime as AccessTimeIcon,
  CloudDownload as CloudDownloadIcon,
  AutoAwesome as AutoAwesomeIcon,
  Refresh as RefreshIcon,
} from '@mui/icons-material';
import { useAuth } from '../../auth/contexts/AuthContext';
import Loader from '../../../components/Loader';

const LearningHubPage = () => {
  const { token } = useAuth();
  const [activeTab, setActiveTab] = useState(0);
  const [searchQuery, setSearchQuery] = useState('');
  const [resources, setResources] = useState([]);
  const [autoGeneratedResults, setAutoGeneratedResults] = useState(null);
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);
  const [recommendations, setRecommendations] = useState({
    personalized: [],
    popular: [],
    recent: []
  });
  const [myProgress, setMyProgress] = useState({ stats: {}, progress: [] });
  const [isLoading, setIsLoading] = useState(false);
  const [selectedResource, setSelectedResource] = useState(null);
  const [openDialog, setOpenDialog] = useState(false);
  const [deleteConfirmDialog, setDeleteConfirmDialog] = useState({ open: false, resourceId: null, resourceTitle: '' });
  const [snackbar, setSnackbar] = useState({ open: false, message: '', severity: 'success' });
  
  // Filters
  const [filters, setFilters] = useState({
    category: 'all',
    difficulty: 'all',
    videoType: 'all',
  });

  const categories = [
    { value: 'all', label: 'All Types' },
    { value: 'video', label: 'Videos' },
    { value: 'article', label: 'Articles' },
    { value: 'tutorial', label: 'Tutorials' },
    { value: 'reference', label: 'References' },
    { value: 'practice', label: 'Practice' },
  ];

  const difficulties = [
    { value: 'all', label: 'All Levels' },
    { value: 'beginner', label: 'Beginner' },
    { value: 'intermediate', label: 'Intermediate' },
    { value: 'advanced', label: 'Advanced' },
  ];

  const videoTypes = [
    { value: 'all', label: 'All Videos' },
    { value: 'video', label: 'Single Videos' },
    { value: 'playlist', label: 'Playlists/Courses' },
  ];

  useEffect(() => {
    // Initial load - no longer fetching subjects
  }, [token]);

  useEffect(() => {
    if (activeTab === 1) {
      fetchRecommendations();
    } else if (activeTab === 2) {
      fetchMyProgress();
    }
  }, [activeTab]);





  const handleSearch = async () => {
    if (!searchQuery.trim()) {
      setAutoGeneratedResults(null);
      setResources([]);
      setSnackbar({ open: true, message: 'Please enter a search query', severity: 'warning' });
      return;
    }

    setIsLoading(true);
    setIsAutoGenerating(true);
    setAutoGeneratedResults(null);
    
    try {
      // Always generate resources from web for search queries
      await handleAutoGenerate();
    } catch (error) {

      setSnackbar({ open: true, message: 'Search failed', severity: 'error' });
    } finally {
      setIsLoading(false);
    }
  };

  const handleAutoGenerate = async () => {
    if (!searchQuery.trim()) {
      setIsAutoGenerating(false);
      return;
    }
    
    setIsAutoGenerating(true);
    try {
      const response = await fetch('/api/learning/auto-generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          query: searchQuery,
          preferredType: filters.category !== 'all' ? filters.category : 'all',
          videoType: filters.videoType !== 'all' ? filters.videoType : undefined,
          difficulty: filters.difficulty !== 'all' ? filters.difficulty : undefined,
        }),
      });

      const result = await response.json();
      if (result.success) {
        // Store the categorized results
        setAutoGeneratedResults(result.data);
        const totalResults = (result.data.academic?.length || 0) + 
                           (result.data.learningPlatforms?.length || 0) + 
                           (result.data.technicalArticles?.length || 0) + 
                           (result.data.videoTutorials?.length || 0);
        setSnackbar({ open: true, message: `Found ${totalResults} resources!`, severity: 'success' });
      } else {
        setSnackbar({ open: true, message: 'No resources found', severity: 'info' });
      }
    } catch (error) {

      setSnackbar({ open: true, message: 'Failed to search web', severity: 'error' });
    } finally {
      setIsAutoGenerating(false);
    }
  };

  const handleSaveGeneratedResource = async (resource) => {
    try {
      const response = await fetch('/api/learning/save-generated', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(resource),
      });

      const result = await response.json();
      if (result.success) {
        // DON'T remove from Explore - keep resources visible in search results
        // Just refresh My Library to show the saved resource there
        await fetchRecommendations();
        
        // Show success feedback
        setSnackbar({ open: true, message: 'Resource saved to My Library!', severity: 'success' });
      } else {
        setSnackbar({ open: true, message: result.message || 'Failed to save resource', severity: 'error' });
      }
    } catch (error) {

      setSnackbar({ open: true, message: 'Failed to save resource', severity: 'error' });
    }
  };

  const handleDeleteResource = async (resourceId, resourceTitle, event) => {
    event.stopPropagation();
    event.preventDefault();

    // Open confirmation dialog
    setDeleteConfirmDialog({
      open: true,
      resourceId: resourceId,
      resourceTitle: resourceTitle
    });
  };

  const confirmDelete = async () => {
    const { resourceId } = deleteConfirmDialog;
    
    try {
      const response = await fetch(`/api/learning/${resourceId}`, {
        method: 'DELETE',
        headers: { 
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
      });

      const result = await response.json();
      
      if (result.success) {
        // Remove from recommendations state immediately
        setRecommendations(prev => ({
          personalized: prev.personalized.filter(r => r._id !== resourceId),
          popular: prev.popular.filter(r => r._id !== resourceId),
          recent: prev.recent.filter(r => r._id !== resourceId),
        }));
        
        // Close dialog
        setDeleteConfirmDialog({ open: false, resourceId: null, resourceTitle: '' });
        
        setSnackbar({ open: true, message: 'Resource removed from library', severity: 'success' });
      } else {
        setSnackbar({ open: true, message: 'Failed to remove: ' + (result.message || 'Unknown error'), severity: 'error' });
      }
    } catch (error) {

      setSnackbar({ open: true, message: 'Error removing resource', severity: 'error' });
    }
  };

  const handleCancelDelete = () => {
    setDeleteConfirmDialog({ open: false, resourceId: null, resourceTitle: '' });
  };

  const fetchRecommendations = async () => {
    setIsLoading(true);
    try {
      const response = await fetch('/api/learning/recommendations', {
        headers: { Authorization: `Bearer ${token}` },
      });
      const result = await response.json();
      if (result.success) {
        setRecommendations(result.data);
      } else {

      }
    } catch (error) {

      // Silently fail - don't show error to user
    } finally {
      setIsLoading(false);
    }
  };

  const fetchMyProgress = async () => {
    setIsLoading(true);
    try {
      const response = await fetch('/api/learning/my-progress', {
        headers: { Authorization: `Bearer ${token}` },
      });
      const result = await response.json();
      if (result.success) {
        setMyProgress(result.data);
      } else {

      }
    } catch (error) {

      // Silently fail - don't show error to user
    } finally {
      setIsLoading(false);
    }
  };

  const handleLike = async (resourceId, event) => {
    event.stopPropagation();
    try {
      const response = await fetch(`/api/learning/${resourceId}/like`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}` },
      });
      const result = await response.json();
      if (result.success) {
        // Update the resource in the list
        const updateResourcesList = (list) =>
          list.map((r) =>
            r._id === resourceId
              ? { ...r, likes: result.data.liked 
                  ? [...(r.likes || []), 'current-user'] 
                  : (r.likes || []).filter(id => id !== 'current-user') }
              : r
          );
        
        setResources(updateResourcesList);
        setRecommendations(prev => ({
          personalized: updateResourcesList(prev.personalized),
          popular: updateResourcesList(prev.popular),
          recent: updateResourcesList(prev.recent),
        }));
      }
    } catch (error) {

    }
  };

  const handleResourceClick = async (resource) => {
    // Open the resource URL directly in a new tab
    if (resource.url || resource.content) {
      const resourceUrl = resource.url || resource.content;
      // Add autoplay for videos
      const finalUrl = resource.category === 'video' 
        ? `${resourceUrl}${resourceUrl.includes('?') ? '&' : '?'}autoplay=1`
        : resourceUrl;
      
      window.open(finalUrl, '_blank', 'noopener,noreferrer');
      
      // Update progress to mark as in-progress if not started
      if (!resource.progress || resource.progress.status === 'not-started') {
        updateProgress(resource._id, { status: 'in-progress' });
      }
    }
  };

  const updateProgress = async (resourceId, data) => {
    try {
      await fetch(`/api/learning/${resourceId}/progress`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(data),
      });
    } catch (error) {

    }
  };

  const handleCompleteResource = async () => {
    if (selectedResource) {
      await updateProgress(selectedResource.resource._id, { 
        status: 'completed',
        progressPercentage: 100 
      });
      setOpenDialog(false);
      fetchMyProgress();
    }
  };

  const getCategoryIcon = (category) => {
    switch (category) {
      case 'video':
        return <PlayArrowIcon />;
      case 'article':
        return <ArticleIcon />;
      case 'quiz-explanation':
        return <QuizIcon />;
      default:
        return <SchoolIcon />;
    }
  };

  const getDifficultyColor = (difficulty) => {
    switch (difficulty) {
      case 'beginner':
        return 'success';
      case 'intermediate':
        return 'warning';
      case 'advanced':
        return 'error';
      default:
        return 'default';
    }
  };

  // Render AI-found resource card (categorized sections)
  const renderAIResource = (resource, index, section) => {
    // Create unique key using multiple identifiers
    const uniqueKey = resource.url || resource.videoId || resource.content || `${section}-${resource.title}-${index}`;
    
    // Check if resource is already saved
    const isSaved = recommendations.personalized.some(saved => 
      saved.url === resource.url || 
      saved.content === resource.content ||
      (resource.videoId && saved.videoId === resource.videoId)
    );
    
    // Different heights for videos vs other content
    const isVideo = resource.category === 'video';
    
    return (
    <Grid key={uniqueKey} size={{ xs: 12, sm: 6, lg: 4 }}>
      <Card 
        sx={{ 
          height: '100%',
          minHeight: isVideo ? '520px' : '320px',
          maxHeight: isVideo ? '600px' : '400px',
          display: 'flex', 
          flexDirection: 'column',
          position: 'relative',
          boxShadow: 2,
          '&:hover': {
            boxShadow: 8,
            transform: 'translateY(-4px)',
            transition: 'all 0.3s ease-in-out'
          }
        }}
      >
        {(resource.thumbnailUrl || resource.thumbnail) && (
          <CardMedia
            component="img"
            height={isVideo ? "180" : "140"}
            image={resource.thumbnailUrl || resource.thumbnail}
            alt={resource.title}
            sx={{
              objectFit: 'cover',
              backgroundColor: '#000',
            }}
          />
        )}
        
        <CardContent sx={{ flexGrow: 1, p: 2, pb: 1 }}>
          <Stack direction="row" spacing={1} sx={{ mb: 1.5, flexWrap: 'wrap', gap: 0.5 }}>
            <Chip 
              icon={getCategoryIcon(resource.category)}
              label={resource.category}
              size="small"
              variant="outlined"
            />
            <Chip 
              label={resource.difficulty}
              size="small"
              color={getDifficultyColor(resource.difficulty)}
            />
            <Chip 
              label={`${resource.score}%`}
              size="small"
              color={resource.score >= 85 ? 'success' : resource.score >= 70 ? 'info' : 'default'}
              icon={<TrendingUpIcon />}
            />
          </Stack>
          
          <Typography variant="h6" gutterBottom sx={{ fontSize: isVideo ? '0.95rem' : '1rem', fontWeight: 600, mb: 1 }}>
            {resource.title}
          </Typography>
          
          <Typography 
            variant="body2" 
            color="text.secondary"
            sx={{ 
              mb: isVideo ? 1.5 : 2,
              fontSize: isVideo ? '0.85rem' : '0.875rem',
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              display: '-webkit-box',
              WebkitLineClamp: isVideo ? 2 : 3,
              WebkitBoxOrient: 'vertical',
            }}
          >
            {resource.description}
          </Typography>
          
          <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mb: 1 }}>
            {resource.topics?.slice(0, 3).map((topic, idx) => (
              <Chip 
                key={idx}
                label={topic}
                size="small"
                variant="outlined"
              />
            ))}
          </Stack>

          <Stack direction="row" spacing={2} sx={{ mt: 1 }}>
            {resource.category === 'video' && resource.channelTitle && (
              <Typography variant="caption" color="text.secondary" sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                📺 {resource.channelTitle}
              </Typography>
            )}
            {resource.category !== 'video' && (
              <Typography variant="caption" color="text.secondary">
                📎 {resource.source}
              </Typography>
            )}
            {resource.estimatedTime && (
              <Typography variant="caption" color="text.secondary">
                ⏱️ {resource.estimatedTime} min
              </Typography>
            )}
          </Stack>
        </CardContent>
        
        <CardActions sx={{ justifyContent: 'space-between', px: 2, pt: 1, pb: 2, mt: 'auto' }}>
          <Button
            size="small"
            href={
              resource.category === 'video' 
                ? `${resource.url || resource.content}${(resource.url || resource.content)?.includes('?') ? '&' : '?'}autoplay=1`
                : resource.url || resource.content
            }
            target="_blank"
            rel="noopener noreferrer"
            startIcon={<PlayArrowIcon />}
            variant="outlined"
            color="primary"
            sx={{ textTransform: 'none' }}
          >
            {resource.category === 'video' ? 'Watch' : 'Open'}
          </Button>
          <Tooltip title={isSaved ? "Already saved in My Library" : "Save to My Library"}>
            <span>
              <Button
                size="small"
                startIcon={isSaved ? <CheckCircleIcon /> : <CloudDownloadIcon />}
                onClick={(e) => {
                  e.stopPropagation();
                  if (!isSaved) {
                    handleSaveGeneratedResource(resource);
                  }
                }}
                variant={isSaved ? "outlined" : "contained"}
                color={isSaved ? "success" : "primary"}
                disabled={isSaved}
                sx={{ textTransform: 'none' }}
              >
                {isSaved ? 'Saved' : 'Save'}
              </Button>
            </span>
          </Tooltip>
        </CardActions>
      </Card>
    </Grid>
  );
  };

  const ResourceCard = ({ resource, showDelete = false }) => {
    const isLiked = resource.likes?.some(like => 
      typeof like === 'string' ? like === 'current-user' : false
    );
    
    return (
      <Card 
        sx={{ 
          height: '100%',
          minHeight: '360px',
          maxHeight: '420px',
          display: 'flex', 
          flexDirection: 'column',
          cursor: 'pointer',
          transition: 'all 0.3s ease-in-out',
          position: 'relative',
          borderRadius: 2,
          overflow: 'hidden',
          boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
          '&:hover': {
            transform: 'translateY(-8px)',
            boxShadow: '0 12px 24px rgba(0,0,0,0.15)',
          }
        }}
        onClick={() => handleResourceClick(resource)}
      >
        {showDelete && (
          <IconButton
            size="small"
            color="error"
            onClick={(e) => handleDeleteResource(resource._id, resource.title, e)}
            sx={{
              position: 'absolute',
              top: 8,
              right: 8,
              zIndex: 10,
              bgcolor: 'rgba(255, 255, 255, 0.95)',
              boxShadow: 2,
              '&:hover': {
                bgcolor: 'error.main',
                color: 'white',
                transform: 'scale(1.1)',
              }
            }}
          >
            <CancelIcon fontSize="small" />
          </IconButton>
        )}
        {resource.thumbnailUrl && (
          <CardMedia
            component="img"
            height="180"
            image={resource.thumbnailUrl}
            alt={resource.title}
            sx={{
              objectFit: 'cover',
              backgroundColor: '#f5f5f5',
            }}
          />
        )}
        {!resource.thumbnailUrl && resource.category === 'video' && (
          <Box
            sx={{
              height: 180,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              bgcolor: 'primary.main',
              color: 'white',
            }}
          >
            <PlayArrowIcon sx={{ fontSize: 60 }} />
          </Box>
        )}
        <CardContent sx={{ flexGrow: 1, p: 2 }}>
          <Stack direction="row" spacing={1} sx={{ mb: 1.5, flexWrap: 'wrap', gap: 0.5 }}>
            <Chip 
              icon={getCategoryIcon(resource.category)}
              label={resource.category}
              size="small"
              variant="outlined"
              color="primary"
            />
            <Chip 
              label={resource.difficulty}
              size="small"
              color={getDifficultyColor(resource.difficulty)}
            />
          </Stack>
          
          <Typography 
            variant="h6" 
            gutterBottom
            sx={{
              fontSize: '1rem',
              fontWeight: 600,
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              display: '-webkit-box',
              WebkitLineClamp: 2,
              WebkitBoxOrient: 'vertical',
              mb: 1,
            }}
          >
            {resource.title}
          </Typography>
          
          <Typography 
            variant="body2" 
            color="text.secondary"
            sx={{ 
              mb: 2,
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              display: '-webkit-box',
              WebkitLineClamp: 2,
              WebkitBoxOrient: 'vertical',
            }}
          >
            {resource.description}
          </Typography>
          
          <Stack direction="row" spacing={1} flexWrap="wrap" sx={{ mb: 1 }}>
            {resource.topics?.slice(0, 3).map((topic, index) => (
              <Chip 
                key={index}
                label={topic}
                size="small"
                variant="outlined"
              />
            ))}
          </Stack>

          {resource.progress && (
            <Box sx={{ mt: 2 }}>
              <Stack direction="row" justifyContent="space-between" sx={{ mb: 0.5 }}>
                <Typography variant="caption" color="text.secondary">
                  Progress: {resource.progress.progressPercentage}%
                </Typography>
                <Typography variant="caption" color="text.secondary">
                  {resource.progress.status}
                </Typography>
              </Stack>
              <LinearProgress 
                variant="determinate" 
                value={resource.progress.progressPercentage} 
              />
            </Box>
          )}
        </CardContent>
        
        <CardActions>
          <Stack direction="row" spacing={1} alignItems="center" sx={{ width: '100%', px: 1 }}>
            <IconButton 
              size="small" 
              onClick={(e) => handleLike(resource._id, e)}
              color={isLiked ? 'error' : 'default'}
            >
              {isLiked ? <FavoriteIcon /> : <FavoriteBorderIcon />}
            </IconButton>
            <Typography variant="caption" color="text.secondary">
              {resource.likes?.length || 0}
            </Typography>
            
            <Box sx={{ flexGrow: 1 }} />
            
            <Stack direction="row" spacing={0.5} alignItems="center">
              <TimerIcon fontSize="small" color="action" />
              <Typography variant="caption" color="text.secondary">
                {resource.estimatedTime} min
              </Typography>
            </Stack>
            
            <Stack direction="row" spacing={0.5} alignItems="center">
              <VisibilityIcon fontSize="small" color="action" />
              <Typography variant="caption" color="text.secondary">
                {resource.views}
              </Typography>
            </Stack>
          </Stack>
        </CardActions>
      </Card>
    );
  };

  return (
    <Box sx={{ 
      p: { xs: 1.5, sm: 2, md: 3 },
      background: 'linear-gradient(to bottom, #f8f9fa 0%, #ffffff 300px)',
      minHeight: '100vh',
    }}>
      {/* Header */}
      <Box sx={{ 
        mb: { xs: 2, sm: 3, md: 4 },
        pb: { xs: 2, sm: 3 },
        borderBottom: '2px solid',
        borderColor: 'primary.main',
      }}>
        <Typography 
          variant="h4" 
          fontWeight="700" 
          sx={{ 
            mb: 1, 
            display: 'flex', 
            alignItems: 'center', 
            gap: { xs: 1, sm: 1.5 },
            color: 'primary.main',
            fontSize: { xs: '1.5rem', sm: '1.75rem', md: '2rem' },
          }}
        >
          <SchoolIcon sx={{ fontSize: { xs: '1.75rem', sm: '2rem', md: '2.5rem' }, color: 'primary.main' }} />
          Learning Hub
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ fontSize: { xs: '0.8rem', sm: '0.875rem' } }}>
          Explore resources, track your progress, and enhance your learning
        </Typography>
      </Box>

      {/* Tabs */}
      <Paper sx={{ 
        mb: { xs: 2, sm: 3 },
        borderRadius: 2,
        boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
      }}>
        <Tabs 
          value={activeTab} 
          onChange={(e, newValue) => setActiveTab(newValue)}
          variant="fullWidth"
          sx={{
            '& .MuiTab-root': {
              fontWeight: 600,
              fontSize: { xs: '0.8rem', sm: '0.9rem', md: '0.95rem' },
              py: { xs: 1.5, sm: 2 },
              minHeight: { xs: 48, sm: 56 },
            },
            '& .Mui-selected': {
              color: 'primary.main',
            },
          }}
        >
          <Tab label="Explore" />
          <Tab label="My Library" />
          <Tab label="Learning Journey" />
        </Tabs>
      </Paper>

      {/* Tab Content */}
      {activeTab === 0 && (
        <Box>
          {/* Search and Filters */}
          <Paper sx={{ 
            p: 3, 
            mb: 3,
            borderRadius: 2,
            boxShadow: '0 2px 12px rgba(0,0,0,0.08)',
          }}>
            <Grid container spacing={2} alignItems="center">
              <Grid size={{ xs: 12, md: 6 }}>
                <TextField
                  fullWidth
                  placeholder="Search for learning resources..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && handleSearch()}
                  InputProps={{
                    startAdornment: (
                      <InputAdornment position="start">
                        <SearchIcon />
                      </InputAdornment>
                    ),
                  }}
                />
              </Grid>
              
              <Grid size={{ xs: 12, sm: 4, md: 2 }}>
                <FormControl fullWidth>
                  <InputLabel>Category</InputLabel>
                  <Select
                    value={filters.category}
                    label="Category"
                    onChange={(e) => setFilters({ ...filters, category: e.target.value })}
                  >
                    {categories.map((cat) => (
                      <MenuItem key={cat.value} value={cat.value}>
                        {cat.label}
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Grid>
              
              <Grid size={{ xs: 12, sm: 4, md: 2 }}>
                <FormControl fullWidth>
                  <InputLabel>Difficulty</InputLabel>
                  <Select
                    value={filters.difficulty}
                    label="Difficulty"
                    onChange={(e) => setFilters({ ...filters, difficulty: e.target.value })}
                  >
                    {difficulties.map((diff) => (
                      <MenuItem key={diff.value} value={diff.value}>
                        {diff.label}
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Grid>

              <Grid size={{ xs: 12, sm: 12, md: 2, lg: 1.5 }}>
                <Button 
                  variant="contained" 
                  fullWidth
                  startIcon={<SearchIcon />}
                  onClick={handleSearch}
                  sx={{ 
                    height: 56,
                    minWidth: { xs: '100%', md: 120 },
                    fontSize: { xs: '0.9rem', md: '0.875rem' },
                  }}
                >
                  Search
                </Button>
              </Grid>
            </Grid>
          </Paper>

          {/* Results */}
          {isLoading ? (
            <Box display="flex" justifyContent="center" py={4}>
              <CircularProgress />
            </Box>
          ) : (
            <>
              {/* Auto-generating indicator */}
              {isAutoGenerating && (
                <Paper sx={{ p: 4, textAlign: 'center', mb: 3 }}>
                  <CircularProgress sx={{ mb: 2 }} />
                  <Typography variant="h6" gutterBottom>
                    Searching the web for best resources...
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Using intelligent algorithms to find and rank quality content from trusted sources
                  </Typography>
                </Paper>
              )}

              {/* Display auto-generated results in 4 sections */}
              {autoGeneratedResults ? (
                <Box>
                  {/* Section 1: Academic Papers/References */}
                  {autoGeneratedResults.academic && autoGeneratedResults.academic.length > 0 && (
                    <Box sx={{ mb: 4 }}>
                      <Typography variant="h5" fontWeight="600" sx={{ mb: 2 }}>
                        Academic Resources
                      </Typography>
                      <Grid container spacing={2}>
                        {autoGeneratedResults.academic.map((resource, index) => renderAIResource(resource, index, 'academic'))}
                      </Grid>
                    </Box>
                  )}

                  {/* Section 2: Learning Platforms */}
                  {autoGeneratedResults.learningPlatforms && autoGeneratedResults.learningPlatforms.length > 0 && (
                    <Box sx={{ mb: 4 }}>
                      <Typography variant="h5" fontWeight="600" sx={{ mb: 2 }}>
                        Learning Platforms
                      </Typography>
                      <Grid container spacing={2}>
                        {autoGeneratedResults.learningPlatforms.map((resource, index) => renderAIResource(resource, index, 'platform'))}
                      </Grid>
                    </Box>
                  )}

                  {/* Section 3: Technical Articles */}
                  {autoGeneratedResults.technicalArticles && autoGeneratedResults.technicalArticles.length > 0 && (
                    <Box sx={{ mb: 4 }}>
                      <Typography variant="h5" fontWeight="600" sx={{ mb: 2 }}>
                        Articles & Documentation
                      </Typography>
                      <Grid container spacing={2}>
                        {autoGeneratedResults.technicalArticles.map((resource, index) => renderAIResource(resource, index, 'article'))}
                      </Grid>
                    </Box>
                  )}

                  {/* Section 4: Video Tutorials */}
                  {autoGeneratedResults.videoTutorials && autoGeneratedResults.videoTutorials.length > 0 && (
                    <Box sx={{ mb: 4 }}>
                      <Typography variant="h5" fontWeight="600" sx={{ mb: 2 }}>
                        Video Tutorials
                      </Typography>
                      <Grid container spacing={2}>
                        {autoGeneratedResults.videoTutorials.map((resource, index) => renderAIResource(resource, index, 'video'))}
                      </Grid>
                    </Box>
                  )}

                  {/* No results message */}
                  {!autoGeneratedResults.academic?.length && 
                   !autoGeneratedResults.learningPlatforms?.length && 
                   !autoGeneratedResults.technicalArticles?.length && 
                   !autoGeneratedResults.videoTutorials?.length && (
                    <Paper sx={{ p: 4, textAlign: 'center' }}>
                      <Typography color="text.secondary">
                        No resources found. Try a different search query.
                      </Typography>
                    </Paper>
                  )}
                </Box>
              ) : !isAutoGenerating && !isLoading && (
                <Paper sx={{ p: 6, textAlign: 'center' }}>
                  <SearchIcon sx={{ fontSize: 80, color: 'text.secondary', mb: 2 }} />
                  <Typography variant="h6" color="text.secondary" gutterBottom>
                    Search for learning resources
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Enter a topic above and click search to find courses, articles, and videos
                  </Typography>
                </Paper>
              )}
            </>
          )}
        </Box>
      )}

      {activeTab === 1 && (
        <Box>
          {isLoading ? (
            <Box display="flex" justifyContent="center" py={4}>
              <CircularProgress />
            </Box>
          ) : (
            <>
              {/* Saved Resources */}
              {recommendations.personalized.length > 0 && (
                <Box sx={{ mb: 4 }}>
                  <Typography variant="h5" gutterBottom fontWeight="600">
                    Saved Resources
                  </Typography>
                  <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                    Resources you've saved from your searches
                  </Typography>
                  <Grid container spacing={3}>
                    {recommendations.personalized.map((resource) => (
                      <Grid key={resource._id} size={{ xs: 12, sm: 6, md: 4 }}>
                        <ResourceCard resource={resource} showDelete={true} />
                      </Grid>
                    ))}
                  </Grid>
                </Box>
              )}

              {/* Popular Resources */}
              {recommendations.popular.length > 0 && (
                <Box sx={{ mb: 4 }}>
                  <Typography variant="h5" gutterBottom fontWeight="600">
                    Popular Resources
                  </Typography>
                  <Grid container spacing={3}>
                    {recommendations.popular.map((resource) => (
                      <Grid key={resource._id} size={{ xs: 12, sm: 6, md: 4 }}>
                        <ResourceCard resource={resource} />
                      </Grid>
                    ))}
                  </Grid>
                </Box>
              )}

              {/* Recent Resources */}
              {recommendations.recent.length > 0 && (
                <Box>
                  <Typography variant="h5" gutterBottom fontWeight="600">
                    Recently Added
                  </Typography>
                  <Grid container spacing={3}>
                    {recommendations.recent.map((resource) => (
                      <Grid key={resource._id} size={{ xs: 12, sm: 6, md: 4 }}>
                        <ResourceCard resource={resource} />
                      </Grid>
                    ))}
                  </Grid>
                </Box>
              )}

              {/* Empty state when no resources saved */}
              {!recommendations.personalized.length && 
               !recommendations.popular.length && 
               !recommendations.recent.length && (
                <Paper sx={{ p: 6, textAlign: 'center' }}>
                  <SchoolIcon sx={{ fontSize: 80, color: 'text.secondary', mb: 2 }} />
                  <Typography variant="h5" color="text.secondary" gutterBottom fontWeight="600">
                    Your Library is Empty
                  </Typography>
                  <Typography variant="body1" color="text.secondary" sx={{ mb: 3 }}>
                    Start exploring and save resources to build your personal learning library
                  </Typography>
                  <Button 
                    variant="contained" 
                    size="large"
                    onClick={() => setActiveTab(0)}
                  >
                    Explore Resources
                  </Button>
                </Paper>
              )}
            </>
          )}
        </Box>
      )}

      {activeTab === 2 && (
        <Box>
          {isLoading ? (
            <Box display="flex" justifyContent="center" py={4}>
              <CircularProgress />
            </Box>
          ) : (
            <>
              {/* Progress Stats */}
              <Grid container spacing={3} sx={{ mb: 4 }}>
                <Grid size={{ xs: 12, sm: 6, md: 3 }}>
                  <Paper sx={{ p: 3, textAlign: 'center' }}>
                    <Typography variant="h4" color="primary" fontWeight="600">
                      {myProgress.stats.total || 0}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      Total Resources
                    </Typography>
                  </Paper>
                </Grid>
                
                <Grid size={{ xs: 12, sm: 6, md: 3 }}>
                  <Paper sx={{ p: 3, textAlign: 'center' }}>
                    <Typography variant="h4" color="success.main" fontWeight="600">
                      {myProgress.stats.completed || 0}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      Completed
                    </Typography>
                  </Paper>
                </Grid>
                
                <Grid size={{ xs: 12, sm: 6, md: 3 }}>
                  <Paper sx={{ p: 3, textAlign: 'center' }}>
                    <Typography variant="h4" color="warning.main" fontWeight="600">
                      {myProgress.stats.inProgress || 0}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      In Progress
                    </Typography>
                  </Paper>
                </Grid>
                
                <Grid size={{ xs: 12, sm: 6, md: 3 }}>
                  <Paper sx={{ p: 3, textAlign: 'center' }}>
                    <Typography variant="h4" color="info.main" fontWeight="600">
                      {myProgress.stats.totalTimeSpent || 0}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      Minutes Learned
                    </Typography>
                  </Paper>
                </Grid>
              </Grid>

              {/* Progress List */}
              <Typography variant="h5" gutterBottom fontWeight="600" sx={{ mb: 2 }}>
                Your Learning Journey
              </Typography>
              
              {myProgress.progress.length > 0 ? (
                <Grid container spacing={3}>
                  {myProgress.progress.map((item) => (
                    <Grid key={item._id} size={{ xs: 12, sm: 6, md: 4 }}>
                      {item.learningResource && <ResourceCard resource={item.learningResource} />}
                    </Grid>
                  ))}
                </Grid>
              ) : (
                <Paper sx={{ p: 4, textAlign: 'center' }}>
                  <Typography variant="h6" color="text.secondary">
                    You haven't started any resources yet
                  </Typography>
                  <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                    Start exploring to track your progress!
                  </Typography>
                  <Button 
                    variant="contained" 
                    onClick={() => setActiveTab(0)}
                  >
                    Explore Resources
                  </Button>
                </Paper>
              )}
            </>
          )}
        </Box>
      )}

      {/* Resource Detail Dialog */}
      <Dialog 
        open={openDialog} 
        onClose={() => setOpenDialog(false)}
        maxWidth="md"
        fullWidth
      >
        {selectedResource && (
          <>
            <DialogTitle>
              <Stack direction="row" spacing={2} alignItems="center">
                <Avatar sx={{ bgcolor: 'primary.main' }}>
                  {getCategoryIcon(selectedResource.resource.category)}
                </Avatar>
                <Box sx={{ flexGrow: 1 }}>
                  <Typography variant="h6">
                    {selectedResource.resource.title}
                  </Typography>
                  <Stack direction="row" spacing={1} sx={{ mt: 0.5 }}>
                    <Chip 
                      label={selectedResource.resource.category}
                      size="small"
                      variant="outlined"
                    />
                    <Chip 
                      label={selectedResource.resource.difficulty}
                      size="small"
                      color={getDifficultyColor(selectedResource.resource.difficulty)}
                    />
                  </Stack>
                </Box>
              </Stack>
            </DialogTitle>
            
            <DialogContent dividers>
              <Typography variant="body1" paragraph>
                {selectedResource.resource.description}
              </Typography>
              
              <Box sx={{ mb: 3 }}>
                <Typography variant="subtitle2" gutterBottom>
                  Estimated Time: {selectedResource.resource.estimatedTime} minutes
                </Typography>
              </Box>

              {selectedResource.resource.topics && selectedResource.resource.topics.length > 0 && (
                <Box sx={{ mb: 3 }}>
                  <Typography variant="subtitle2" gutterBottom>
                    Topics Covered:
                  </Typography>
                  <Stack direction="row" spacing={1} flexWrap="wrap">
                    {selectedResource.resource.topics.map((topic, index) => (
                      <Chip key={index} label={topic} size="small" />
                    ))}
                  </Stack>
                </Box>
              )}

              <Divider sx={{ my: 2 }} />

              <Box sx={{ mb: 2 }}>
                <Typography variant="h6" gutterBottom>
                  Content
                </Typography>
                {selectedResource.resource.contentType === 'url' || selectedResource.resource.contentType === 'video-url' ? (
                  <Button 
                    variant="outlined" 
                    href={selectedResource.resource.content}
                    target="_blank"
                    startIcon={<PlayArrowIcon />}
                  >
                    Open Resource
                  </Button>
                ) : (
                  <Typography variant="body2" sx={{ whiteSpace: 'pre-wrap' }}>
                    {selectedResource.resource.content}
                  </Typography>
                )}
              </Box>

              {selectedResource.progress && (
                <Box sx={{ mt: 3 }}>
                  <Typography variant="subtitle2" gutterBottom>
                    Your Progress: {selectedResource.progress.progressPercentage}%
                  </Typography>
                  <LinearProgress 
                    variant="determinate" 
                    value={selectedResource.progress.progressPercentage} 
                    sx={{ mb: 1 }}
                  />
                  <Typography variant="caption" color="text.secondary">
                    Status: {selectedResource.progress.status}
                  </Typography>
                </Box>
              )}
            </DialogContent>
            
            <DialogActions>
              <Button onClick={() => setOpenDialog(false)}>
                Close
              </Button>
              {selectedResource.progress?.status !== 'completed' && (
                <Button 
                  variant="contained" 
                  onClick={handleCompleteResource}
                  startIcon={<CheckCircleIcon />}
                >
                  Mark as Complete
                </Button>
              )}
            </DialogActions>
          </>
        )}
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog
        open={deleteConfirmDialog.open}
        onClose={() => setDeleteConfirmDialog({ open: false, resourceId: null, resourceTitle: '' })}
        maxWidth="xs"
        PaperProps={{
          sx: {
            borderRadius: 2,
          }
        }}
      >
        <DialogTitle>Delete Resource?</DialogTitle>
        <DialogContent>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
            {deleteConfirmDialog.resourceTitle}
          </Typography>
        </DialogContent>
        <DialogActions sx={{ p: 2, gap: 1 }}>
          <Button 
            onClick={handleCancelDelete}
            variant="text"
            color="inherit"
          >
            Cancel
          </Button>
          <Button 
            onClick={confirmDelete}
            variant="contained"
            color="error"
            autoFocus
          >
            Delete
          </Button>
        </DialogActions>
      </Dialog>

      {/* Snackbar for notifications */}
      <Snackbar
        open={snackbar.open}
        autoHideDuration={3000}
        onClose={() => setSnackbar({ ...snackbar, open: false })}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert 
          onClose={() => setSnackbar({ ...snackbar, open: false })} 
          severity={snackbar.severity}
          sx={{ width: '100%' }}
        >
          {snackbar.message}
        </Alert>
      </Snackbar>
    </Box>
  );
};

export default LearningHubPage;
